server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 100M;

    # Tipos MIME para video
    types {
        text/html                             html htm;
        text/css                              css;
        application/javascript                js;
        application/json                      json;
        image/jpeg                            jpg jpeg;
        image/png                             png;
        image/svg+xml                         svg;
        image/webp                            webp;
        video/mp4                             mp4;
        video/webm                            webm;
        font/woff                             woff;
        font/woff2                            woff2;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
